apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: food-delivery-ingress
  namespace: food-delivery
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/group.name: food-delivery
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: food-delivery-backend
                port:
                  number: 4000

          - path: /images
            pathType: Prefix
            backend:
              service:
                name: food-delivery-backend
                port:
                  number: 4000

          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: food-delivery-admin
                port:
                  number: 80

          - path: /
            pathType: Prefix
            backend:
              service:
                name: food-delivery-frontend
                port:
                  number: 80
